// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpuggogxhqbtqilplexs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwdWdnb2d4aHFidHFpbHBsZXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzk2MDIsImV4cCI6MjA2NzgxNTYwMn0.Z5ealu3Q9YM5Pw5QVqOw6LpsF1QJ2ObaBn87zUs2k9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});